# Generated by Django 4.1 on 2022-08-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productservice',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
