# Generated by Django 4.1 on 2022-08-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.IntegerField()),
                ('happycustomers', models.IntegerField()),
                ('products', models.IntegerField()),
                ('purity', models.IntegerField()),
            ],
        ),
    ]
