# Generated by Django 4.1 on 2022-08-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_aboutmembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutExperts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='experts/')),
                ('job', models.CharField(max_length=255)),
            ],
        ),
    ]
