# Generated by Django 4.1 on 2022-08-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_aboutexperts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('smalltitle', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='services/')),
                ('miniservicetitle', models.CharField(max_length=255)),
                ('miniservicetext', models.TextField()),
            ],
        ),
    ]
