# Generated by Django 4.1 on 2022-08-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_miniservices_remove_services_miniservicetext_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basicprice', models.IntegerField()),
                ('standardprice', models.IntegerField()),
                ('premiumprice', models.IntegerField()),
                ('basictext', models.CharField(max_length=255)),
                ('standardtext', models.CharField(max_length=255)),
                ('premiumtext', models.CharField(max_length=255)),
            ],
        ),
    ]
