# Generated by Django 4.1 on 2022-08-06 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_homeaboutservice_homeabout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeabout',
            name='service',
        ),
    ]
