# Generated by Django 4.1 on 2022-08-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_order_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
