# Generated by Django 4.1 on 2022-08-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobilenumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('adress', models.CharField(max_length=255)),
            ],
        ),
    ]
