# Generated by Django 4.1 on 2022-08-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mobilenumber',
            new_name='mobile',
        ),
        migrations.AddField(
            model_name='profile',
            name='shipping',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
