# Generated by Django 4.1 on 2022-08-08 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_aboutslider_blogslider_cartslider_checkoutslider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
