# Generated by Django 4.1 on 2022-08-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_profile_email_remove_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='AboutSlider',
        ),
        migrations.DeleteModel(
            name='BlogSlider',
        ),
        migrations.DeleteModel(
            name='CartSlider',
        ),
        migrations.DeleteModel(
            name='CheckoutSlider',
        ),
        migrations.DeleteModel(
            name='ContactSlider',
        ),
        migrations.DeleteModel(
            name='ServiceSlider',
        ),
        migrations.DeleteModel(
            name='ShopSlider',
        ),
    ]
